/*
 * Filename: sc_engine_type.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * description: Signal class containing the engine data
 * name: sc_engine
 * shortname: engine
 *
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "sc_engine_type.h"



/* USER CODE START SC_ENGINE_INCLUDE */
#include "led.h"
/* USER CODE END SC_ENGINE_INCLUDE */




/* USER CODE START SC_ENGINE_USERDEFINITIONS */

/* USER CODE END SC_ENGINE_USERDEFINITIONS */


/*****************************************************************************************
 *************** Port Wrapper Implementation for SC_ENGINE signal  ****************
 *****************************************************************************************/
 
 
/**
 * Default OUT driver API
 */
inline RC_t SC_ENGINE_driverOut(const SC_ENGINE_data_t  *const data)
{
	/* USER CODE START driverOutSC_ENGINE */
    //Scale application data to drive format
	//Write scaled data to driver
    if(data->engineLightValue>0)
    {
        Engine_PWM_WriteCompare(data->engineLightValue);
        //LED_RGB_Set(data->engineLightValue); //No smooth transition
    }
    else
    {
        LED_RGB_Set(0);
        LED_Set(LED_RED, 0);
    }
	return RC_SUCCESS;
	/* USER CODE END driverOutSC_ENGINE */
}



