/*
 * Filename: sc_joystick_type.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * description: Signal class containing the joystick position value
 * name: sc_joystick
 * shortname: joystick
 *
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "sc_joystick_type.h"


/* USER CODE START SC_JOYSTICK_INCLUDE */
# include "joystick.h"
/* USER CODE END SC_JOYSTICK_INCLUDE */




/* USER CODE START SC_JOYSTICK_USERDEFINITIONS */

/* USER CODE END SC_JOYSTICK_USERDEFINITIONS */


/*****************************************************************************************
 *************** Port Wrapper Implementation for SC_JOYSTICK signal  ****************
 *****************************************************************************************/
 
 

/**
 * Default IN driver API
 */
inline RC_t SC_JOYSTICK_driverIn(SC_JOYSTICK_data_t *const data)
{
	/* USER CODE START driverInSC_JOYSTICK */
    sint8_t horizontal_x;
    sint8_t horizontal_y;
	//Read data from the MCAL driver
    JOYSTICK_ReadPosition(&horizontal_x, &horizontal_y);
	//Scale it to the application type
    data->joystick_x = horizontal_x;
    data->joystick_y = horizontal_y;
	return RC_SUCCESS;
	/* USER CODE END driverInSC_JOYSTICK */
}



