
/*
 * Filename: swc_engine.h
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * Description: Software component that contains the engine runnable
 */

#ifndef _H_DEFINE_SWC_ENGINE
#define _H_DEFINE_SWC_ENGINE

#include "project.h"
#include "global.h"
#include "rte_types.h"

/* USER CODE START SWC_ENGINE_INCLUDES */

/* USER CODE END SWC_ENGINE_INCLUDES */



/* USER CODE START SWC_ENGINE_USERDEFINITIONS */

/* USER CODE END SWC_ENGINE_USERDEFINITIONS */


/*
 * component: swc_engine
 * cycletime: 100
 * description: Runnable that copies the speed signal value to the engine signal value and call the driver pushport()
 * events: 
 * name: ENGINE_setEngine_run
 * shortname: setEngine
 * signalIN: so_speed
 * signalOUT: so_engine
 * task: tsk_io
 */
void ENGINE_setEngine_run(RTE_event ev);


#endif