
/*
 * Filename: swc_joystick.h
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * Description: Software component that reads the joystick data every 10ms
 */

#ifndef _H_DEFINE_SWC_JOYSTICK
#define _H_DEFINE_SWC_JOYSTICK

#include "project.h"
#include "global.h"
#include "rte_types.h"

/* USER CODE START SWC_JOYSTICK_INCLUDES */

/* USER CODE END SWC_JOYSTICK_INCLUDES */



/* USER CODE START SWC_JOYSTICK_USERDEFINITIONS */

/* USER CODE END SWC_JOYSTICK_USERDEFINITIONS */


/*
 * component: swc_joystick
 * cycletime: 10
 * description: Runnable that reads the joystick value every 10ms and updates through API pullport()
 * events: 
 * name: JOYSTICK_readJoystick_run
 * shortname: readJoystick
 * signalIN: 
 * signalOUT: so_joystick
 * task: tsk_io
 */
void JOYSTICK_readJoystick_run(RTE_event ev);


#endif