/*
 * Filename: swc_brakelight.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * description: Software component that contains the brakelight runnable
 * name: swc_brakelight
 * shortname: brakelight
 *
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "swc_brakelight.h"
#include "watchdog_timer.h"



/* USER CODE START SWC_BRAKELIGHT_INCLUDE */

/* USER CODE END SWC_BRAKELIGHT_INCLUDE */


#include "sp_common.h"

/* USER CODE START SWC_BRAKELIGHT_USERDEFINITIONS */

/* USER CODE END SWC_BRAKELIGHT_USERDEFINITIONS */



/*
 * component: swc_brakelight
 * cycletime: 0
 * description: Runnable that is updated on speed signal value change
 * events: ev_speed_onData
 * name: BRAKELIGHT_setBrakeLight_run
 * shortname: setBrakeLight
 * signalIN: so_speed
 * signalOUT: so_brakelight
 * task: tsk_io
 */
void BRAKELIGHT_setBrakeLight_run(RTE_event ev){
	
	/* USER CODE START BRAKELIGHT_setBrakeLight_run */
    
    SC_SPEED_data_t speed = RTE_SC_SPEED_get(&SO_SPEED_signal);
    SC_BRAKELIGHT_data_t myBrake;
    if(speed.speedValue==0)
    {
       myBrake.brakeLightValue = 1;
    }
    else
    {
       myBrake.brakeLightValue = 0;
    }
    
    RC_t returnState1, returnState2;
    returnState1 = RTE_SC_BRAKELIGHT_set(&SO_BRAKELIGHT_signal, myBrake);
    if(returnState1 == RC_SUCCESS)
    { 
        returnState2 = RTE_SC_BRAKELIGHT_pushPort(&SO_BRAKELIGHT_signal);
        if(returnState2 != RC_SUCCESS)
        {
            UART_LOG_PutString("Error updating the brake signal driver\r\n");
        }
    }
    else
    {
        UART_LOG_PutString("Brake signal not updated \r\n");
    }
    
    WD_Alive(run_brake_pos);
    /* USER CODE END BRAKELIGHT_setBrakeLight_run */
}

/* USER CODE START SWC_BRAKELIGHT_FUNCTIONS */

/* USER CODE END SWC_BRAKELIGHT_FUNCTIONS */

