/*
 * Filename: swc_control.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * description: Software component that sets the speed signal value
 * name: swc_control
 * shortname: control
 *
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "swc_control.h"
#include "watchdog_timer.h"


/* USER CODE START SWC_CONTROL_INCLUDE */

/* USER CODE END SWC_CONTROL_INCLUDE */


#include "sp_common.h"

/* USER CODE START SWC_CONTROL_USERDEFINITIONS */

/* USER CODE END SWC_CONTROL_USERDEFINITIONS */



/*
 * component: swc_control
 * cycletime: 0
 * description: Runnable that checks the joystick signal and depending upon that value speed signal is updated
 * events: ev_joystick_onData
 * name: CONTROL_calcControl_run
 * shortname: calcControl
 * signalIN: so_joystick
 * signalOUT: so_speed
 * task: tsk_control
 */
void CONTROL_calcControl_run(RTE_event ev){
	
	/* USER CODE START CONTROL_calcControl_run */
    /* 
    SC_SPEED_data_t mySpeed = SC_SPEED_INIT_DATA;
    mySpeed.speedValue = 10;
    RTE_SC_SPEED_set(&SO_SPEED_signal, mySpeed);
    */
    
    SC_JOYSTICK_data_t joyStick = RTE_SC_JOYSTICK_get(&SO_JOYSTICK_signal);
    sint8_t myJoystick=joyStick.joystick_x;
    
    SC_SPEED_data_t mySpeed;
    boolean_t speedUpdate= FALSE;
    
    if(myJoystick > 0)
    {
        mySpeed.speedValue=2*myJoystick;
        speedUpdate = TRUE;
    }
    if(myJoystick < 0)
    {
        mySpeed.speedValue = 0;  
        speedUpdate = TRUE;
    }
    RC_t returnState;
    // check if speed signal is updated by verifying the joystick movement
    //RTE_SC_SPEED_set(&SO_SPEED_signal,mySpeed);
    //WD_Alive(run_control_pos);
    if(speedUpdate)
    {
        returnState = RTE_SC_SPEED_set(&SO_SPEED_signal,mySpeed);    
    }
    else
    {
        returnState = RTE_SC_SPEED_set(&SO_SPEED_signal,mySpeed);
        RTE_SC_SPEED_incAge(&SO_SPEED_signal, 1);  // No joystick movement so speed is 0 => increase the age
    }
    if(returnState != RC_SUCCESS)
    {
        UART_LOG_PutString("Error updating the speed signal\r\n");
    }
    WD_Alive(run_control_pos);
    
    /*
    SC_SPEED_data_t currentSpeed = RTE_SC_SPEED_get(&SO_SPEED_signal);
    // check if speed signal is updated by verifying the joystick movement
    if(speedUpdate)
    {
        // check if speed signal is updated recently 
        if(mySpeed.speedValue!=currentSpeed.speedValue)
        {
            returnState = RTE_SC_SPEED_set(&SO_SPEED_signal,mySpeed);    
            if(returnState != RC_SUCCESS)
            {
                UART_LOG_PutString("Error updating the speed signal\r\n");
            }
        }
        else
        {
            returnState = RTE_SC_SPEED_set(&SO_SPEED_signal,mySpeed);
            RTE_SC_SPEED_incAge(&SO_SPEED_signal, 1);  // No real update => increase the age
        }
    }
    else
    {
        returnState = RTE_SC_SPEED_set(&SO_SPEED_signal,mySpeed);
        RTE_SC_SPEED_incAge(&SO_SPEED_signal, 1);  // No joystick movement so speed is 0 => increase the age
    }
    */
    /* USER CODE END CONTROL_calcControl_run */
}

/* USER CODE START SWC_CONTROL_FUNCTIONS */

/* USER CODE END SWC_CONTROL_FUNCTIONS */

