/*
 * Filename: swc_engine.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * description: Software component that contains the engine runnable
 * name: swc_engine
 * shortname: engine
 *
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "swc_engine.h"
#include "watchdog_timer.h"

#include "stdio.h"
/* USER CODE START SWC_ENGINE_INCLUDE */
#define SPEED_SIGNAL_MAX_AGE_MS 10  // Define what "too old" means
/* USER CODE END SWC_ENGINE_INCLUDE */


#include "sp_common.h"

/* USER CODE START SWC_ENGINE_USERDEFINITIONS */

/* USER CODE END SWC_ENGINE_USERDEFINITIONS */



/*
 * component: swc_engine
 * cycletime: 100
 * description: Runnable that copies the speed signal value to the engine signal value and call the driver pushport()
 * events: 
 * name: ENGINE_setEngine_run
 * shortname: setEngine
 * signalIN: so_speed
 * signalOUT: so_engine
 * task: tsk_io
 */
void ENGINE_setEngine_run(RTE_event ev){
	
	/* USER CODE START ENGINE_setEngine_run */
    SC_SPEED_data_t speed = RTE_SC_SPEED_get(&SO_SPEED_signal);
    SC_ENGINE_data_t myEngine;
    if(RTE_SC_SPEED_getAge(&SO_SPEED_signal) < SPEED_SIGNAL_MAX_AGE_MS )
    {
        //char buffer[100];
        //snprintf(buffer, sizeof(buffer), "Age:%u\r\n", SO_SPEED_signal.age);
        //UART_LOG_PutString(buffer);
        //UART_LOG_PutString("New Signal\r\n");
        myEngine.engineLightValue=speed.speedValue;
    }
    else
    {
        //char buffer[100];
        //snprintf(buffer, sizeof(buffer), "Age:%u\r\n", SO_SPEED_signal.age);
        //UART_LOG_PutString(buffer);
        //UART_LOG_PutString("Old signal\r\n");
        myEngine.engineLightValue=0;
    }
    RC_t returnState1, returnState2;
    returnState1 = RTE_SC_ENGINE_set(&SO_ENGINE_signal, myEngine);
    if(returnState1 == RC_SUCCESS)
    { 
        returnState2 = RTE_SC_ENGINE_pushPort(&SO_ENGINE_signal);
        if(returnState2 != RC_SUCCESS)
        {
            UART_LOG_PutString("Error updating the engine signal driver\r\n");
        }
    }
    else
    {
        UART_LOG_PutString("Engine signal not updated \r\n");
    }
    
    WD_Alive(run_engine_pos);
    /* USER CODE END ENGINE_setEngine_run */
}

/* USER CODE START SWC_ENGINE_FUNCTIONS */

/* USER CODE END SWC_ENGINE_FUNCTIONS */

